# Generated by Django 5.2.14 on 2026-08-08 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='number',
        ),
    ]
