# Generated by Django 5.2.14 on 2026-08-08 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_remove_userprofile_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='lasttName',
            new_name='lastName',
        ),
    ]
