# Generated by Django 5.2.14 on 2026-08-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_rename_lasttname_userprofile_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='courses',
            field=models.CharField(default='python'),
        ),
    ]
