# Generated by Django 5.2.14 on 2026-08-08 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0005_remove_userprofile_courses_userprofile_add'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='add',
            new_name='Date_of_joining',
        ),
    ]
