# Generated by Django 5.2.14 on 2026-08-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0006_rename_add_userprofile_date_of_joining'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='courses',
            field=models.CharField(default='python'),
        ),
    ]
