# Generated by Django 5.2.14 on 2026-08-08 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0007_userprofile_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='Date_of_joining',
        ),
    ]
