# Generated by Django 5.2.14 on 2026-08-08 11:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0008_remove_userprofile_date_of_joining'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Date_of_joining',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
