# Generated by Django 5.2.14 on 2026-08-08 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0009_userprofile_date_of_joining'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='Date_of_joining',
        ),
    ]
