# Generated by Django 5.2.14 on 2026-08-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0010_remove_userprofile_date_of_joining'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Date_of_joining',
            field=models.CharField(default='today', max_length=100),
            preserve_default=False,
        ),
    ]
