# Generated by Django 5.2.14 on 2026-08-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0012_remove_userprofile_date_of_joining'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Date_of_Enquiry',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contactNumber',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
