# Generated by Django 5.2.14 on 2026-08-13 11:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0013_userprofile_date_of_enquiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Date_of_Enquiry',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='courses',
            field=models.CharField(null=True),
        ),
    ]
